# Generated by Django 4.1.2 on 2022-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_product_catagory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('add', models.CharField(default='', max_length=50)),
                ('pin', models.CharField(default='', max_length=6)),
                ('comm', models.DateField(default='', max_length=500)),
            ],
        ),
    ]
