# Generated by Django 4.1.2 on 2022-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comm',
            field=models.CharField(default='', max_length=500),
        ),
    ]
